/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProgramJava;

public class App {
   
    

    public static void main(String[] args) {
       //Demonstração de alguns tipos de dados
       
       //SOMA
       int num1, num2, num3;
       
       num1 = 10;
       num2 = 20;
       num3 = num1 + num2;
       System.out.println("O resultado da soma é: " + num3);
       
       
        //SUBTAÇÃO
             
       num1 = 10;
       num2 = 20;
       num3 = num1 - num2;
       System.out.println("O resultado da subtração é: " + num3);
       
        //MULTIPLICAÇÃO
              
       num1 = 10;
       num2 = 20;
       num3 = num1 * num2;
       System.out.println("O resultado da multiplicação é: " + num3);
       
       
        //DIVISÃO      
       
       num1 = 10;
       num2 = 20;
       num3 = num1 / num2;
       System.out.println("O resultado da divisão é: " + num3);
       
       System.out.println("------------------------------------------");
       //INCREMENTANDO (SOMANDO DE 1 EM 1)
       
       num1 = 0;
         while (num1 <= 10){
             num1++;
             System.out.println(num1);
         }
         
         System.out.println("------------------------------------------");
         //DECREMENTANDO (SUBTRAINDO DE 1 EM 1)
       
       num1 = 10;
         while (num1 >= 0){
             num1--;
             System.out.println(num1);
         }
        System.out.println("------------------------------------------");
         // OPERADORES RELACIONAIS > < >= <= != =
         
         //TESTANDO IGUALDADE
         int x, y;
         x = 10;
         y = 10;
                 
        if (x == y){
            System.out.println("X e Y são iguais");
        }
        System.out.println("------------------------------------------");
        
        //TESTANDO DESIGUALDADE
         int a, b;
         a = 10;
         b = 30;
                 
        if (a != b){
            System.out.println("A e B são diferentes");
        }
        
        
        System.out.println("------------------------------------------");
        
        //TESTANDO MAIOR
         int c, d;
         c = 10;
         d = 30;
                 
        if (c > d){
            System.out.println("C é maior que D");
        } else {
            System.out.println("C é menor que D");
        }
        
        System.out.println("------------------------------------------");
        //OPERADORES LÓGICOS
        //&&
        int n1 = 10;
        int n2 = 5;
        int n3 = 20, n4 = 5;
        
        if((n1 > n3) && (n2 == n4)){
        System.out.println("Primeira opção satisfeita");
    } else {
            System.out.println("Segunda opção satisfeita");
        }
            
        System.out.println("------------------------------------------");
         //||
        int x1 = 10;
        int x2 = 5;
        int x3 = 20, x4 = 5;
        
        if((n1 > n3) || (n2 == n4)){
        System.out.println("Primeira opção satisfeita");
    } else {
            System.out.println("Segunda opção satisfeita");
        }
    }
}
